# Generated by Django 3.1.7 on 2021-03-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand1', models.IntegerField(max_length=100)),
                ('operand2', models.IntegerField(max_length=100)),
                ('operations', models.CharField(max_length=200)),
                ('result', models.IntegerField(max_length=200)),
            ],
        ),
    ]
