# Generated by Django 3.1.7 on 2021-03-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0002_auto_20210329_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsmodel',
            name='operand1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operationsmodel',
            name='operand2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operationsmodel',
            name='operation',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='operationsmodel',
            name='result',
            field=models.IntegerField(),
        ),
    ]
