# Generated by Django 3.1.7 on 2021-03-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0003_auto_20210330_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsmodel',
            name='result',
        ),
        migrations.AlterField(
            model_name='operationsmodel',
            name='operand1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='operationsmodel',
            name='operand2',
            field=models.FloatField(),
        ),
    ]
