# Generated by Django 3.1.7 on 2021-03-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0004_auto_20210330_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsmodel',
            name='answer',
            field=models.FloatField(default=0),
        ),
    ]
